/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as CotizacionesRouteImport } from './routes/cotizaciones'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LineaDeTiempoRouteImport } from './routes/linea-de-tiempo'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NuevaOtRouteImport } from './routes/nueva-ot'
import { Route as NuevoTicketRouteImport } from './routes/nuevo-ticket'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as TodasLasOtRouteImport } from './routes/todas-las-ot'
import { Route as MesaDeAyudaIndexRouteImport } from './routes/mesa-de-ayuda/index'
import { Route as MesaDeAyudaSeguimientoRouteImport } from './routes/mesa-de-ayuda/seguimiento'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const CotizacionesRoute = CotizacionesRouteImport.update({
  id: '/cotizaciones',
  path: '/cotizaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LineaDeTiempoRoute = LineaDeTiempoRouteImport.update({
  id: '/linea-de-tiempo',
  path: '/linea-de-tiempo',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NuevaOtRoute = NuevaOtRouteImport.update({
  id: '/nueva-ot',
  path: '/nueva-ot',
  getParentRoute: () => rootRouteImport,
} as any)
const NuevoTicketRoute = NuevoTicketRouteImport.update({
  id: '/nuevo-ticket',
  path: '/nuevo-ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const TodasLasOtRoute = TodasLasOtRouteImport.update({
  id: '/todas-las-ot',
  path: '/todas-las-ot',
  getParentRoute: () => rootRouteImport,
} as any)
const MesaDeAyudaIndexRoute = MesaDeAyudaIndexRouteImport.update({
  id: '/mesa-de-ayuda/',
  path: '/mesa-de-ayuda/',
  getParentRoute: () => rootRouteImport,
} as any)
const MesaDeAyudaSeguimientoRoute = MesaDeAyudaSeguimientoRouteImport.update({
  id: '/mesa-de-ayuda/seguimiento',
  path: '/mesa-de-ayuda/seguimiento',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/configuracion': typeof ConfiguracionRoute
  '/cotizaciones': typeof CotizacionesRoute
  '/dashboard': typeof DashboardRoute
  '/linea-de-tiempo': typeof LineaDeTiempoRoute
  '/login': typeof LoginRoute
  '/nueva-ot': typeof NuevaOtRoute
  '/nuevo-ticket': typeof NuevoTicketRoute
  '/tickets': typeof TicketsRoute
  '/todas-las-ot': typeof TodasLasOtRoute
  '/mesa-de-ayuda/seguimiento': typeof MesaDeAyudaSeguimientoRoute
  '/mesa-de-ayuda/': typeof MesaDeAyudaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/configuracion': typeof ConfiguracionRoute
  '/cotizaciones': typeof CotizacionesRoute
  '/dashboard': typeof DashboardRoute
  '/linea-de-tiempo': typeof LineaDeTiempoRoute
  '/login': typeof LoginRoute
  '/nueva-ot': typeof NuevaOtRoute
  '/nuevo-ticket': typeof NuevoTicketRoute
  '/tickets': typeof TicketsRoute
  '/todas-las-ot': typeof TodasLasOtRoute
  '/mesa-de-ayuda/seguimiento': typeof MesaDeAyudaSeguimientoRoute
  '/mesa-de-ayuda': typeof MesaDeAyudaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/configuracion': typeof ConfiguracionRoute
  '/cotizaciones': typeof CotizacionesRoute
  '/dashboard': typeof DashboardRoute
  '/linea-de-tiempo': typeof LineaDeTiempoRoute
  '/login': typeof LoginRoute
  '/nueva-ot': typeof NuevaOtRoute
  '/nuevo-ticket': typeof NuevoTicketRoute
  '/tickets': typeof TicketsRoute
  '/todas-las-ot': typeof TodasLasOtRoute
  '/mesa-de-ayuda/seguimiento': typeof MesaDeAyudaSeguimientoRoute
  '/mesa-de-ayuda/': typeof MesaDeAyudaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clientes'
    | '/configuracion'
    | '/cotizaciones'
    | '/dashboard'
    | '/linea-de-tiempo'
    | '/login'
    | '/nueva-ot'
    | '/nuevo-ticket'
    | '/tickets'
    | '/todas-las-ot'
    | '/mesa-de-ayuda/seguimiento'
    | '/mesa-de-ayuda/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clientes'
    | '/configuracion'
    | '/cotizaciones'
    | '/dashboard'
    | '/linea-de-tiempo'
    | '/login'
    | '/nueva-ot'
    | '/nuevo-ticket'
    | '/tickets'
    | '/todas-las-ot'
    | '/mesa-de-ayuda/seguimiento'
    | '/mesa-de-ayuda'
  id:
    | '__root__'
    | '/'
    | '/clientes'
    | '/configuracion'
    | '/cotizaciones'
    | '/dashboard'
    | '/linea-de-tiempo'
    | '/login'
    | '/nueva-ot'
    | '/nuevo-ticket'
    | '/tickets'
    | '/todas-las-ot'
    | '/mesa-de-ayuda/seguimiento'
    | '/mesa-de-ayuda/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientesRoute: typeof ClientesRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  CotizacionesRoute: typeof CotizacionesRoute
  DashboardRoute: typeof DashboardRoute
  LineaDeTiempoRoute: typeof LineaDeTiempoRoute
  LoginRoute: typeof LoginRoute
  NuevaOtRoute: typeof NuevaOtRoute
  NuevoTicketRoute: typeof NuevoTicketRoute
  TicketsRoute: typeof TicketsRoute
  TodasLasOtRoute: typeof TodasLasOtRoute
  MesaDeAyudaSeguimientoRoute: typeof MesaDeAyudaSeguimientoRoute
  MesaDeAyudaIndexRoute: typeof MesaDeAyudaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotizaciones': {
      id: '/cotizaciones'
      path: '/cotizaciones'
      fullPath: '/cotizaciones'
      preLoaderRoute: typeof CotizacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linea-de-tiempo': {
      id: '/linea-de-tiempo'
      path: '/linea-de-tiempo'
      fullPath: '/linea-de-tiempo'
      preLoaderRoute: typeof LineaDeTiempoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nueva-ot': {
      id: '/nueva-ot'
      path: '/nueva-ot'
      fullPath: '/nueva-ot'
      preLoaderRoute: typeof NuevaOtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nuevo-ticket': {
      id: '/nuevo-ticket'
      path: '/nuevo-ticket'
      fullPath: '/nuevo-ticket'
      preLoaderRoute: typeof NuevoTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todas-las-ot': {
      id: '/todas-las-ot'
      path: '/todas-las-ot'
      fullPath: '/todas-las-ot'
      preLoaderRoute: typeof TodasLasOtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mesa-de-ayuda/': {
      id: '/mesa-de-ayuda/'
      path: '/mesa-de-ayuda'
      fullPath: '/mesa-de-ayuda/'
      preLoaderRoute: typeof MesaDeAyudaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mesa-de-ayuda/seguimiento': {
      id: '/mesa-de-ayuda/seguimiento'
      path: '/mesa-de-ayuda/seguimiento'
      fullPath: '/mesa-de-ayuda/seguimiento'
      preLoaderRoute: typeof MesaDeAyudaSeguimientoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientesRoute: ClientesRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  CotizacionesRoute: CotizacionesRoute,
  DashboardRoute: DashboardRoute,
  LineaDeTiempoRoute: LineaDeTiempoRoute,
  LoginRoute: LoginRoute,
  NuevaOtRoute: NuevaOtRoute,
  NuevoTicketRoute: NuevoTicketRoute,
  TicketsRoute: TicketsRoute,
  TodasLasOtRoute: TodasLasOtRoute,
  MesaDeAyudaSeguimientoRoute: MesaDeAyudaSeguimientoRoute,
  MesaDeAyudaIndexRoute: MesaDeAyudaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
